# Logitech F310 controller
# D<>X button (located on the back panel) must be set to D
# Mode button must not be selected (LED is off)

axes:
  0: "Left Horizontal"
  1: "Left Vertical"
  2: "Right Horizontal"
  3: "Right Vertical"
  4: "Cross Key Horizontal"
  5: "Cross Key Vertical"

buttons:
  0: "X"
  1: "A"
  2: "B"
  3: "Y"
  4: "LB"
  5: "RB"
  6: "LT"
  7: "RT"
  8: "BACK"
  9: "START"
  10: "L3"
  11: "R3"